### ISSUE TITLE
error in running recognition model ?

### ISSUE THREAD

**Issue by ankur7721** [doc-analysis/TableBank#10]
While running this command after having recognition model in my local `model.pt`

` python translate.py -model model.pt -src recognition.jpg -output pred.txt -replace_unk -verbose`

```
Traceback (most recent call last):
  File "translate.py", line 48, in <module>
    main(opt)
  File "translate.py", line 19, in main
    translator = build_translator(opt, report_score=True)
  File "/home/ubuntu/OpenNMT-py/onmt/translate/translator.py", line 28, in build_translator
    fields, model, model_opt = load_test_model(opt)
  File "/home/ubuntu/OpenNMT-py/onmt/model_builder.py", line 95, in load_test_model
    map_location=lambda storage, loc: storage)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python2.7/site-packages/torch/serialization.py", line 387, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/home/ubuntu/anaconda3/envs/pytorch_p36/lib/python2.7/site-packages/torch/serialization.py", line 574, in _load
    result = unpickler.load()
```
`pytorch 0.4.1`
`py36_cuda9.2.148_cudnn7.1.4_1`

Can someone tell what could be error ?

**Comment by ankur7721** [comment]
Has anyone tried running table recognition model ?

**Comment by rahulsinghpatel** [comment]
hi  Minghao Li,
  can you please tell me how to use your pre-trained model for Table Structure Recognition.
currently, I am using An image which contains a table and I am trying to extract table out of that. But it is giving me am an empty table.

Script to run code:
OpenNMT-py admin$ python translate.py -data_type img -model model.pt -src_dir data/im2text/images -src data/im2text/src-test.txt -output pred.txt -max_length 150 -beam_size 5 -verbose

output:
 <tabular> <tbody> <tr> <tdy> <tdy> <tdy> </tr> <tr> <tdy> <tdy> <tdy> </tr> <tr> <tdy> <tdy> <tdy> </tr> <tr> <tdy> <tdy> <tdy> </tr> <tr> <tdy> <tdy> <tdy> </tr> <tr> <tdy> <tdy> <tdy> </tr> <tr> <tdy> <tdy> <tdy> </tr> </tbody> </tabular>

can you please help me with this. I am stuck on this?

References:
http://opennmt.net/OpenNMT-py/im2text.html
https://github.com/OpenNMT/OpenNMT-py
https://conversationhub.blob.core.windows.net/tablebank/model_zoo/Recognition_all_without_copyright/model.pt

**Comment by ankur7721** [comment]
Hi @rahulsinghpatel 
Can you tell me what's in `data/im2text/src-test.txt` ?

**Comment by liminghao1630** [comment]
@ankur7721 
Follow the instruction on this link and see the help of -train_src.
http://opennmt.net/OpenNMT-py/im2text.html

**Comment by liminghao1630** [comment]
hi @rahulsinghpatel ,
what's the meaning of empty table?  can you show me the output in pred.txt?
This model require the input image is a whole table without anything else.

**Comment by ankur7721** [comment]
@liminghao1630 I am using this command to run recognition model `python translate.py -data_type img -model model.pt -src_dir test_img/ -src src.txt -output pred.txt` wherein content of src.txt is this

`recognition.jpg`

and folder structure is 
```
test_img/
        - recognition.jpg
```

This is the error I am getting

[2019-08-05 09:59:07,739 INFO] Translating shard 0.
test_img/
```
Traceback (most recent call last):
  File "translate.py", line 48, in <module>
    main(opt)
  File "translate.py", line 32, in main
    attn_debug=opt.attn_debug
  File "/home/ubuntu/OpenNMT-py/onmt/translate/translator.py", line 328, in translate
    for batch in data_iter:
  File "/home/ubuntu/OpenNMT-py/onmt/inputters/inputter.py", line 608, in __iter__
    self.device)
  File "/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/torchtext/data/batch.py", line 34, in __init__
    setattr(self, name, field.process(batch, device=device))
  File "/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/torchtext/data/field.py", line 201, in process
    tensor = self.numericalize(padded, device=device)
  File "/home/ubuntu/anaconda3/envs/python3/lib/python3.6/site-packages/torchtext/data/field.py", line 312, in numericalize
    "https://github.com/pytorch/text/issues".format(self.dtype))
ValueError: Specified Field dtype float32 can not be used with use_vocab=False because we do not know how to numericalize it. Please raise an issue at https://github.com/pytorch/text/issues

```

**Comment by MuruganR96** [comment]
i was bit confused. please once explain me @liminghao @rahulsinghpatel :)

i was tried this way.

```
python drive/My\ Drive/OpenNMT-py/translate.py -data_type img -model drive/My\ Drive/Pretrained_Word_Embeddings/detectron_table_detection/model.pt -src_dir drive/My\ Drive/datasets/table_dataset_sample/8.jpg \
  -output pred.txt -max_length 150 -beam_size 5 -gpu 0 -verbose



```
i am getting same issue. i don't know what is -src_dir & -src

```
usage: translate.py [-h] [-config CONFIG] [-save_config SAVE_CONFIG] --model
                    MODEL [MODEL ...] [--fp32] [--avg_raw_probs]
                    [--data_type DATA_TYPE] --src SRC [--src_dir SRC_DIR]
                    [--tgt TGT] [--shard_size SHARD_SIZE] [--output OUTPUT]
                    [--report_bleu] [--report_rouge] [--report_time]
                    [--dynamic_dict] [--share_vocab]
                    [--random_sampling_topk RANDOM_SAMPLING_TOPK]
                    [--random_sampling_temp RANDOM_SAMPLING_TEMP]
                    [--seed SEED] [--beam_size BEAM_SIZE]
                    [--min_length MIN_LENGTH] [--max_length MAX_LENGTH]
                    [--max_sent_length] [--stepwise_penalty]
                    [--length_penalty {none,wu,avg}] [--ratio RATIO]
                    [--coverage_penalty {none,wu,summary}] [--alpha ALPHA]
                    [--beta BETA] [--block_ngram_repeat BLOCK_NGRAM_REPEAT]
                    [--ignore_when_blocking IGNORE_WHEN_BLOCKING [IGNORE_WHEN_BLOCKING ...]]
                    [--replace_unk] [--phrase_table PHRASE_TABLE] [--verbose]
                    [--log_file LOG_FILE]
                    [--log_file_level {CRITICAL,ERROR,WARNING,INFO,DEBUG,NOTSET,50,40,30,20,10,0}]
                    [--attn_debug] [--dump_beam DUMP_BEAM] [--n_best N_BEST]
                    [--batch_size BATCH_SIZE] [--gpu GPU]
                    [--sample_rate SAMPLE_RATE] [--window_size WINDOW_SIZE]
                    [--window_stride WINDOW_STRIDE] [--window WINDOW]
                    [--image_channel_size {3,1}]
translate.py: error: the following arguments are required: --src/-src
```

here docuentation ([Image to text ](http://opennmt.net/OpenNMT-py/im2text.html)) they said,

```
python translate.py -data_type img -model demo-model_acc_x_ppl_x_e13.pt -src_dir data/im2text/images \
					-src data/im2text/src-test.txt -output pred.txt -max_length 150 -beam_size 5 -gpu 0 -verbose
```
`-src_dir: The directory containing the images.`

then why i need **-src data/im2text/src-test.txt** ?

we want image to text. but src why txt. what is that can any one clarify me. 

Thank you all

**Comment by MuruganR96** [comment]
@ankur7721  your question, answer here.
**-src data/im2text/src-test.txt** means the input image location give to this txtfile.

Refer here, https://github.com/OpenNMT/OpenNMT-py/issues/1533#issue-482436956

**Comment by MuruganR96** [comment]
hi @rahulsinghpatel,
i am also getting poor result. not extracting the text from the source image.

```
[2019-08-19 17:50:44,610 INFO] Translating shard 0.
/usr/local/lib/python3.6/dist-packages/torchtext/data/field.py:359: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  var = torch.tensor(arr, dtype=self.dtype, device=device)


SENT 1: None
PRED 1: <tabular> <tbody> <tr> <tdy> <tdy> <tdy> <tdy> <tdy> <tdy> <tdy> <tdy> <tdy> <tdy> <tdy> <tdy> </tr> <tr> <tdy> <tdy> <tdy> <tdy> <tdy> <tdy> <tdy> <tdy> <tdy> <tdy> <tdy> <tdy> </tr> <tr> <tdy> <tdy> <tdy> <tdy> <tdy> <tdy> <tdy> <tdy> <tdy> <tdy> <tdy> <tdn> </tr> <tr> <tdy> <tdy> <tdy> <tdy> <tdy> <tdy> <tdy> <tdy> <tdy> <tdy> <tdy> <tdn> </tr> <tr> <tdy> <tdy> <tdy> <tdy> <tdy> <tdy> <tdy> <tdy> <tdy> <tdy> <tdy> <tdn> </tr> <tr> <tdy> <tdy> <tdy> <tdy> <tdy> <tdy> <tdy> <tdy> <tdy> <tdy> <tdy> <tdn> </tr> <tr> <tdy> <tdy> <tdy> <tdy> <tdy> <tdy> <tdy> <tdy> <tdy> <tdy> <tdy> <tdn> </tr> <tr> <tdy> <tdy> <tdy> <tdy> <tdy> <tdy> <tdy> <tdy> <tdy> <tdy> <tdy> <tdn> </tr> </tbody> </tabular>
PRED SCORE: -1.2848
PRED AVG SCORE: -0.0111, PRED PPL: 1.0111

my output here
```

**Comment by interviewBubble** [comment]
**For clarification I am giving sample output:**
this is generating only table markup. NO DATA
Like this:
<tabular> <tbody> <tr> <tdy> <tdy> <tdy> <tdy> <tdy> </tr> <tr> <tdy> <tdy> <tdy> <tdy> <tdy> </tr> <tr> <tdy> <tdy> <tdy> <tdy> <tdy> </tr> <tr> <tdy> <tdy> <tdy> <tdy> <tdy> </tr> </tbody> </tabular>

**Comment by sanku015** [comment]
i am getting this error "AssertionError: Cannot use _dir with TextDataReader." while running translate.py

**Comment by lwd45** [comment]
> **For clarification I am giving sample output:**
> this is generating only table markup. NO DATA
> Like this:
> `<tabular> <tbody> <tr> <tdy> <tdy> <tdy> <tdy> <tdy> </tr> <tr> <tdy> <tdy> <tdy> <tdy> <tdy> </tr> <tr> <tdy> <tdy> <tdy> <tdy> <tdy> </tr> <tr> <tdy> <tdy> <tdy> <tdy> <tdy> </tr> </tbody> </tabular>`
> 
> tbody - table body.
> tr - table row.
> tdy - cell with data.
> tdn - cell with no data.
> 
> Hope this is helpful.

Do you know how I can turn these tags into images so that I can easily observe if there are any errors?

**Comment by kbrajwani** [comment]
@liminghao1630 @MuruganR96 
hey i am also getting the empty cell. anyone have figure it out?
this is my colab notebook. i have cropped only table area still model not able to get text.
https://colab.research.google.com/drive/1xeOQ5IUpwjDmCU6orwHd2hP3coOaau1t?usp=sharing

**Comment by LastMonody** [comment]
> 我收到此错误“断言错误：无法将 _dir 与 TextDataReader 一起使用”。运行 translate.py 时

Has this been solved? I'm stuck here, too
