### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'astype'

### ISSUE THREAD

**Issue by omerarshad** [doc-analysis/TableBank#13]
Getting this error while trying to infer 

INFO net.py:  96: rpn_bbox_pred_fpn2_w [+ momentum] loaded from weights file into gpu_0/rpn_bbox_pred_fpn2_w: (12, 256, 1, 1)
INFO net.py:  96: rpn_bbox_pred_fpn2_b [+ momentum] loaded from weights file into gpu_0/rpn_bbox_pred_fpn2_b: (12,)
INFO net.py:  96: fc6_w [+ momentum] loaded from weights file into gpu_0/fc6_w: (1024, 12544)
INFO net.py:  96: fc6_b [+ momentum] loaded from weights file into gpu_0/fc6_b: (1024,)
INFO net.py:  96: fc7_w [+ momentum] loaded from weights file into gpu_0/fc7_w: (1024, 1024)
INFO net.py:  96: fc7_b [+ momentum] loaded from weights file into gpu_0/fc7_b: (1024,)
INFO net.py:  96: cls_score_w [+ momentum] loaded from weights file into gpu_0/cls_score_w: (2, 1024)
INFO net.py:  96: cls_score_b [+ momentum] loaded from weights file into gpu_0/cls_score_b: (2,)
INFO net.py:  96: bbox_pred_w [+ momentum] loaded from weights file into gpu_0/bbox_pred_w: (8, 1024)
INFO net.py:  96: bbox_pred_b [+ momentum] loaded from weights file into gpu_0/bbox_pred_b: (8,)
INFO net.py: 133: pred_b preserved in workspace (unused)
INFO net.py: 133: pred_w preserved in workspace (unused)
[I net_dag_utils.cc:102] Operator graph pruning prior to chain compute took: 7.9674e-05 secs
[I net_dag_utils.cc:102] Operator graph pruning prior to chain compute took: 5.9175e-05 secs
INFO infer_simple.py: 147: Processing /images/ -> /tmp/detectron-tablebank/.pdf
Traceback (most recent call last):
  File "detectron/tools/infer_simple.py", line 185, in <module>
    main(args)
  File "detectron/tools/infer_simple.py", line 153, in main
    model, im, None, timers=timers
  File "/content/detectron/detectron/core/test.py", line 66, in im_detect_all
    model, im, cfg.TEST.SCALE, cfg.TEST.MAX_SIZE, boxes=box_proposals
  File "/content/detectron/detectron/core/test.py", line 137, in im_detect_bbox
    inputs, im_scale = _get_blobs(im, boxes, target_scale, target_max_size)
  File "/content/detectron/detectron/core/test.py", line 946, in _get_blobs
    blob_utils.get_image_blob(im, target_scale, target_max_size)
  File "/content/detectron/detectron/utils/blob.py", line 52, in get_image_blob
    im, cfg.PIXEL_MEANS, target_scale, target_max_size
  File "/content/detectron/detectron/utils/blob.py", line 108, in prep_im_for_blob
    im = im.astype(np.float32, copy=False)
AttributeError: 'NoneType' object has no attribute 'astype'

**Comment by xuyuhui666** [comment]
it seems that path wrong,you can check the img path or debug the code
