### ISSUE TITLE
KeyError: 'Non-existent config key: _BASE_' 

### ISSUE THREAD

**Issue by omrastogi** [doc-analysis/TableBank#33]
I am running the code on google colab, and running: 
```
!python detectron/tools/infer_simple.py --cfg /content/All_X101.yaml --output-dir /tmp/detectron-tablebank --image-ext jpg \
    --wts /content/model_final.pth /content/drive/MyDrive/TableBank/Image
```

The error is: 
```
Found Detectron ops lib: /usr/local/lib/python3.7/dist-packages/torch/lib/libcaffe2_detectron_ops_gpu.so
[E init_intrinsics_check.cc:44] CPU feature avx is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
[E init_intrinsics_check.cc:44] CPU feature avx2 is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
[E init_intrinsics_check.cc:44] CPU feature fma is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
Traceback (most recent call last):
  File "detectron/tools/infer_simple.py", line 185, in <module>
    main(args)
  File "detectron/tools/infer_simple.py", line 125, in main
    merge_cfg_from_file(args.cfg)
  File "/content/detectron/detectron/core/config.py", line 1152, in merge_cfg_from_file
    _merge_a_into_b(yaml_cfg, __C)
  File "/content/detectron/detectron/core/config.py", line 1202, in _merge_a_into_b
    raise KeyError('Non-existent config key: {}'.format(full_key))
KeyError: 'Non-existent config key: _BASE_'
```

**Comment by omrastogi** [comment]
The new configuration file for detectron2 and I was running detectron code.
